export interface Salary {
  id: string,
  basicSalary: string,
  bonus: string,
  lunchSalary: string,
  trafficSalary: string,
  allSalary?: string,
  pensionBase: string,
  pensionPer: string,
  createDate: string,
  medicalBase: string,
  medicalPer: string,
  accumulationFundBase: string,
  accumulationFundPer: string,
  name: string,
}

export interface Department {
  id?: string,
  name: string,
  parentId?: string,
  depPath?: string,
  enabled?: string,
  isParent?: string,
  children?: string,
  result?: string,
}

export interface Emp {
  id: number,
  name: string,
  gender: string,
  birthday: string,
  idCard: string,
  wedlock: string,
  nationId: number,
  nativePlace: string,
  politicId: number,
  email: string,
  phone: string,
  address: string,
  departmentId: number,
  jobLevelId: number,
  posId: number,
  engageForm: string,
  tiptopDegree: string,
  specialty: string,
  school: string,
  beginDate: string,
  workState: string,
  workID: string,
  contractTerm: number,
  conversionTime: string,
  notWorkDate?: string,
  beginContract: string,
  endContract: string,
  workAge?: string,
  salaryId: number,
  nation?: string,
  politicsStatus?: string,
  department: Department,
  joblevel?: string,
  position?: string,
  salary: Salary,
}


